# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('chapa', models.CharField(blank=True, max_length=150)),
                ('numero', models.IntegerField(blank=True, max_length=3)),
                ('proposta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('DHInicio', models.DateTimeField()),
                ('DHFim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVencendor', models.CharField(blank=True, max_length=200)),
                ('numeroVencedor', models.IntegerField(blank=True, max_length=3)),
                ('qntVotos', models.IntegerField(blank=True)),
                ('qntVotorVencedor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tolken',
            fields=[
                ('idTolken', models.AutoField(primary_key=True, serialize=False)),
                ('idEleitor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.Eleitor')),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeVaga', models.CharField(blank=True, max_length=200)),
                ('QntVaga', models.IntegerField(blank=True)),
            ],
        ),
    ]
