# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(blank=True)),
                ('branco', models.BooleanField(default=False, verbose_name='branco')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.Vagas'),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='eleicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.Eleicao'),
        ),
        migrations.AddField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleicao.Candidato'),
        ),
    ]
